name    'example42-firewall'
version '2.1.3'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
summary 'Puppet firewall abstraction meta module'
description 'This module provides abstraction defines to firewall resources managed by Puppet modules. It is used in the Example42 modules set but can be imported and used in other setups. According to the firewall tool used it may have the relevant module as dependency'
dependency 'example42/puppi', '>= 2.0.0'
dependency 'example42/iptables', '>= 2.0.0'

